[build]
  publish = "public"
  command = "hugo --gc --themesDir themes"
  
[build.environment]
   HUGO_VERSION = "0.92.1"
   HUGO_THEME = "revetive"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'master']