backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
collections:
  - name: "aboutus" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "about us" # Used in the UI, ie.: "New Post"
    folder: "content/english/aboutus" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page header image", name: "page_header_bg", widget: "image" }
      - { label: "Meta description", name: "metadescription", widget: "text" }
      - { label: "About title", name: "abouttitle", widget: "string" }
      - { label: boximage1, name: boximage1, widget: image}
      - { label: boximage2, name: boximage2, widget: image}
      - { label: boxcontent1, name: boxcontent1, widget: string}
      - { label: boxcontent2, name: boxcontent2, widget: string}
      - { label: "boxtitle1", name: "boxtitle1", widget: "string" }
      - { label: "boxtitle2", name: "boxtitle2", widget: "string" }
      - { label: "Intro", name: "intro", widget: "markdown" }